### ISSUE TITLE
Component not found by dagger2 in multimodule application

### ISSUE THREAD

**Issue by TheReprator** [JulianEzequiel/dagger-multi-module#1]
I know the issue is not related to this repo, but just for some assistance i am posting my issue here

This is related to dagger transistive dependencies, i.e. https://github.com/google/dagger/issues/970

This is my reference project
https://github.com/TheReprator/BugReproduceFragmentFactory

**Comment by JulianEzequiel** [comment]
Some comments here, I don't know if it will help but maybe:

- Why are you trying to inject some values in the GlobalApp when there are no attributes that require to be injected?
- You're working with Factories and, truly, I really don't know how they work.
- There are some modules that don't provide any dependencies and makes the code a bit harder to read, can you clean them please?

When you're ready, I'll check again if I can help you. Sorry!

**Comment by TheReprator** [comment]
Thanks for your quick and humble response, 

I had removed as per comment, but i don't find any uselesss module right now,
> * There are some modules that don't provide any dependencies and makes the code a bit harder to read, can you clean them please?

Also i had added you as collaborator, that may ease the work.
Once again thanks.

**Comment by JulianEzequiel** [comment]
Well, I took a look at some documentation and what I think that's happening here is that you're trying to modularize something that cannot be modularized.

The dependencies that have to be used in the modules are circular always, so you will no te able to make this injection work.

Maybe you want to check if you can modify the dependency graph, or if you can modify the modules to be less-independent. Otherwise, you will need another module that _centralizes_ the dependencies and both **DashBoard** and **home** modules use it.

Hope it will help, if you have another doubt just tell me
